POST http://localhost:3000/as/data HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMmYyOWM0MjRkZGI4ODE5OTFjMGI2MCIsImtpbmQiOiJhY2Nlc3NfdG9rZW4iLCJpYXQiOjE2MzA3NjMyNzEsImV4cCI6MTYzMDg0OTY3MX0.PnzjIvpCC7mk5_PuvgONdmOodznU7bkY_tRFQ7LoiOw

{
  "request_id": "1b50uu97c0assfefmi46720d40e9fedd83a485c2b1a3b64992093761420b48bb3f576930ad89a85c95600",
  "node_id": "894CFA85-2AC5-4758-A86B-3E12B88F17DF",
  "type": "response_result",
  "reference_id": "123123213",
  "success": true,
  "error": {
    "code": 0,
    "message": "test"
  }
}

###
GET http://localhost:9092/flushStat HTTP/1.1